### ISSUE TITLE
Storage for INTRO.avi

### ISSUE THREAD

**Issue by chronoss09** [dekkit/PS2-Intro-Loader-Public-Releases#1]
Possible to store and read the file into the MC ?
mc:/intro.avi

**Comment by dekkit** [comment]
Unfortunately the MC speeds are terrible, I think thats why SMS player was never setup to read from it.

Technically possible, but the video encoding quality would need to be a such a very very low quality  that it wouldnt look good at all.

USB and HDD are the best methods (SMB was too slow to initiate).
